version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      # TB client must be updated alongside TB container
      - dependency-name: tigerbeetle-node

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
